### ISSUE TITLE
Won't install

### ISSUE THREAD

**Issue by danielbayley** [geneanet/linter-htmlcs#6]
~~~ sh
> apm install linter-htmlcs
Installing linter-htmlcs to /Users/Dan/Library/Application Support/Atom/packages ✗
No available version compatible with the installed Atom version: 1.12.7
~~~
macOS 10.12.3
Atom 1.14.0-beta3

**Comment by ChristopheBoucaut** [comment]
Are you sure for your version ? The error message is provided by atom directly and not the plugin. Maybe a conflict with multiple versions on your OS.

**Comment by danielbayley** [comment]
Strange… No problems now with Atom 1.16.0-beta0.
